PRAGMA foreign_keys = ON;

CREATE TABLE IF NOT EXISTS User (
    UserID   INTEGER PRIMARY KEY AUTOINCREMENT,
    Name     TEXT    NOT NULL,
    Email    TEXT    NOT NULL UNIQUE,
    Password TEXT    NOT NULL,
    JoinDate TEXT    NOT NULL
);

CREATE TABLE IF NOT EXISTS Book (
    BookID  INTEGER PRIMARY KEY AUTOINCREMENT,
    Title   TEXT    NOT NULL,
    Author  TEXT,
    Genre   TEXT
);

CREATE TABLE IF NOT EXISTS List (
    ListID  INTEGER PRIMARY KEY AUTOINCREMENT,
    UserID  INTEGER NOT NULL UNIQUE,
    FOREIGN KEY (UserID) REFERENCES User(UserID) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS References_ (
    BookID    INTEGER NOT NULL,
    ListID    INTEGER NOT NULL,
    Status    TEXT    NOT NULL CHECK(Status IN ('want to read','currently reading','finished')),
    DateAdded TEXT    NOT NULL,
    StartDate TEXT,
    EndDate   TEXT,
    PRIMARY KEY (BookID, ListID),
    FOREIGN KEY (BookID) REFERENCES Book(BookID) ON DELETE CASCADE,
    FOREIGN KEY (ListID) REFERENCES List(ListID) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS Read (
    UserID  INTEGER NOT NULL,
    BookID  INTEGER NOT NULL,
    PRIMARY KEY (UserID, BookID),
    FOREIGN KEY (UserID) REFERENCES User(UserID) ON DELETE CASCADE,
    FOREIGN KEY (BookID) REFERENCES Book(BookID) ON DELETE CASCADE
);
